# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/203/bin/cmake

# The command to remove a file.
RM = /snap/cmake/203/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/deka/Academic/gemini

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/deka/Academic/gemini

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/203/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/203/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/deka/Academic/gemini/CMakeFiles /home/deka/Academic/gemini/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/deka/Academic/gemini/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chord

# Build rule for target.
chord: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chord
.PHONY : chord

# fast build rule for target.
chord/fast:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/build
.PHONY : chord/fast

#=============================================================================
# Target rules for targets named libAUTH

# Build rule for target.
libAUTH: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libAUTH
.PHONY : libAUTH

# fast build rule for target.
libAUTH/fast:
	$(MAKE) -f bin_auth/CMakeFiles/libAUTH.dir/build.make bin_auth/CMakeFiles/libAUTH.dir/build
.PHONY : libAUTH/fast

#=============================================================================
# Target rules for targets named libNODE

# Build rule for target.
libNODE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libNODE
.PHONY : libNODE

# fast build rule for target.
libNODE/fast:
	$(MAKE) -f bin_node/CMakeFiles/libNODE.dir/build.make bin_node/CMakeFiles/libNODE.dir/build
.PHONY : libNODE/fast

#=============================================================================
# Target rules for targets named libSERVICES

# Build rule for target.
libSERVICES: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libSERVICES
.PHONY : libSERVICES

# fast build rule for target.
libSERVICES/fast:
	$(MAKE) -f bin_services/CMakeFiles/libSERVICES.dir/build.make bin_services/CMakeFiles/libSERVICES.dir/build
.PHONY : libSERVICES/fast

#=============================================================================
# Target rules for targets named libSERVER

# Build rule for target.
libSERVER: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libSERVER
.PHONY : libSERVER

# fast build rule for target.
libSERVER/fast:
	$(MAKE) -f bin_serverUtils/CMakeFiles/libSERVER.dir/build.make bin_serverUtils/CMakeFiles/libSERVER.dir/build
.PHONY : libSERVER/fast

Chord/src/address.o: Chord/src/address.cpp.o

.PHONY : Chord/src/address.o

# target to build an object file
Chord/src/address.cpp.o:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/address.cpp.o
.PHONY : Chord/src/address.cpp.o

Chord/src/address.i: Chord/src/address.cpp.i

.PHONY : Chord/src/address.i

# target to preprocess a source file
Chord/src/address.cpp.i:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/address.cpp.i
.PHONY : Chord/src/address.cpp.i

Chord/src/address.s: Chord/src/address.cpp.s

.PHONY : Chord/src/address.s

# target to generate assembly for a file
Chord/src/address.cpp.s:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/address.cpp.s
.PHONY : Chord/src/address.cpp.s

Chord/src/chord.o: Chord/src/chord.cpp.o

.PHONY : Chord/src/chord.o

# target to build an object file
Chord/src/chord.cpp.o:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/chord.cpp.o
.PHONY : Chord/src/chord.cpp.o

Chord/src/chord.i: Chord/src/chord.cpp.i

.PHONY : Chord/src/chord.i

# target to preprocess a source file
Chord/src/chord.cpp.i:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/chord.cpp.i
.PHONY : Chord/src/chord.cpp.i

Chord/src/chord.s: Chord/src/chord.cpp.s

.PHONY : Chord/src/chord.s

# target to generate assembly for a file
Chord/src/chord.cpp.s:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/chord.cpp.s
.PHONY : Chord/src/chord.cpp.s

Chord/src/fingerTable.o: Chord/src/fingerTable.cpp.o

.PHONY : Chord/src/fingerTable.o

# target to build an object file
Chord/src/fingerTable.cpp.o:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/fingerTable.cpp.o
.PHONY : Chord/src/fingerTable.cpp.o

Chord/src/fingerTable.i: Chord/src/fingerTable.cpp.i

.PHONY : Chord/src/fingerTable.i

# target to preprocess a source file
Chord/src/fingerTable.cpp.i:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/fingerTable.cpp.i
.PHONY : Chord/src/fingerTable.cpp.i

Chord/src/fingerTable.s: Chord/src/fingerTable.cpp.s

.PHONY : Chord/src/fingerTable.s

# target to generate assembly for a file
Chord/src/fingerTable.cpp.s:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/fingerTable.cpp.s
.PHONY : Chord/src/fingerTable.cpp.s

Chord/src/successorTable.o: Chord/src/successorTable.cpp.o

.PHONY : Chord/src/successorTable.o

# target to build an object file
Chord/src/successorTable.cpp.o:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/successorTable.cpp.o
.PHONY : Chord/src/successorTable.cpp.o

Chord/src/successorTable.i: Chord/src/successorTable.cpp.i

.PHONY : Chord/src/successorTable.i

# target to preprocess a source file
Chord/src/successorTable.cpp.i:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/successorTable.cpp.i
.PHONY : Chord/src/successorTable.cpp.i

Chord/src/successorTable.s: Chord/src/successorTable.cpp.s

.PHONY : Chord/src/successorTable.s

# target to generate assembly for a file
Chord/src/successorTable.cpp.s:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/successorTable.cpp.s
.PHONY : Chord/src/successorTable.cpp.s

Chord/src/tableBase.o: Chord/src/tableBase.cpp.o

.PHONY : Chord/src/tableBase.o

# target to build an object file
Chord/src/tableBase.cpp.o:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/tableBase.cpp.o
.PHONY : Chord/src/tableBase.cpp.o

Chord/src/tableBase.i: Chord/src/tableBase.cpp.i

.PHONY : Chord/src/tableBase.i

# target to preprocess a source file
Chord/src/tableBase.cpp.i:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/tableBase.cpp.i
.PHONY : Chord/src/tableBase.cpp.i

Chord/src/tableBase.s: Chord/src/tableBase.cpp.s

.PHONY : Chord/src/tableBase.s

# target to generate assembly for a file
Chord/src/tableBase.cpp.s:
	$(MAKE) -f CMakeFiles/chord.dir/build.make CMakeFiles/chord.dir/Chord/src/tableBase.cpp.s
.PHONY : Chord/src/tableBase.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... chord"
	@echo "... edit_cache"
	@echo "... libAUTH"
	@echo "... libNODE"
	@echo "... libSERVICES"
	@echo "... libSERVER"
	@echo "... Chord/src/address.o"
	@echo "... Chord/src/address.i"
	@echo "... Chord/src/address.s"
	@echo "... Chord/src/chord.o"
	@echo "... Chord/src/chord.i"
	@echo "... Chord/src/chord.s"
	@echo "... Chord/src/fingerTable.o"
	@echo "... Chord/src/fingerTable.i"
	@echo "... Chord/src/fingerTable.s"
	@echo "... Chord/src/successorTable.o"
	@echo "... Chord/src/successorTable.i"
	@echo "... Chord/src/successorTable.s"
	@echo "... Chord/src/tableBase.o"
	@echo "... Chord/src/tableBase.i"
	@echo "... Chord/src/tableBase.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

